package com.alexschutz.scrybary

val symbols = mapOf(
            ("{T}" to R.drawable.sym_t),
            ("{Q}" to R.drawable.sym_q),
            ("{E}" to R.drawable.sym_e),
            ("{PW}" to R.drawable.sym_pw),
            ("{CHAOS}" to R.drawable.sym_chaos),
            ("{A}" to R.drawable.sym_a),
            ("{X}" to R.drawable.sym_x),
            ("{Y}" to R.drawable.sym_y),
            ("{Z}" to R.drawable.sym_z),
            ("{0}" to R.drawable.sym_0),
            ("{½}" to R.drawable.sym_half),
            ("{1}" to R.drawable.sym_1),
            ("{2}" to R.drawable.sym_2),
            ("{3}" to R.drawable.sym_3),
            ("{4}" to R.drawable.sym_4),
            ("{5}" to R.drawable.sym_5),
            ("{6}" to R.drawable.sym_6),
            ("{7}" to R.drawable.sym_7),
            ("{8}" to R.drawable.sym_8),
            ("{9}" to R.drawable.sym_9),
            ("{10}" to R.drawable.sym_10),
            ("{11}" to R.drawable.sym_11),
            ("{12}" to R.drawable.sym_12),
            ("{13}" to R.drawable.sym_13),
            ("{14}" to R.drawable.sym_14),
            ("{15}" to R.drawable.sym_15),
            ("{16}" to R.drawable.sym_16),
            ("{17}" to R.drawable.sym_17),
            ("{18}" to R.drawable.sym_18),
            ("{19}" to R.drawable.sym_19),
            ("{20}" to R.drawable.sym_20),
            ("{100}" to R.drawable.sym_100),
            ("{1000000}" to R.drawable.sym_1000000),
            ("{∞}" to R.drawable.sym_infinity),
            ("{W/U}" to R.drawable.sym_wu),
            ("{W/B}" to R.drawable.sym_wb),
            ("{B/R}" to R.drawable.sym_br),
            ("{B/G}" to R.drawable.sym_bg),
            ("{U/B}" to R.drawable.sym_ub),
            ("{U/R}" to R.drawable.sym_ur),
            ("{R/G}" to R.drawable.sym_rg),
            ("{R/W}" to R.drawable.sym_rw),
            ("{G/W}" to R.drawable.sym_gw),
            ("{G/U}" to R.drawable.sym_gu),
            ("{2/W}" to R.drawable.sym_2w),
            ("{2/U}" to R.drawable.sym_2u),
            ("{2/B}" to R.drawable.sym_2b),
            ("{2/R}" to R.drawable.sym_2r),
            ("{2/G}" to R.drawable.sym_2g),
            ("{P}" to R.drawable.sym_p),
            ("{W/P}" to R.drawable.sym_wp),
            ("{U/P}" to R.drawable.sym_up),
            ("{B/P}" to R.drawable.sym_bp),
            ("{R/P}" to R.drawable.sym_rp),
            ("{G/P}" to R.drawable.sym_gp),
            ("{HW}" to R.drawable.sym_hw),
            ("{HR}" to R.drawable.sym_hr),
            ("{W}" to R.drawable.sym_w),
            ("{U}" to R.drawable.sym_u),
            ("{B}" to R.drawable.sym_b),
            ("{R}" to R.drawable.sym_r),
            ("{G}" to R.drawable.sym_g),
            ("{C}" to R.drawable.sym_c),
            ("{S}" to R.drawable.sym_s),
        )



